#!/usr/bin/env bash
# Generate the GN build configuration for Quick Browser.
#
#   configure-quick-browser.sh [workdir] [outdir]
#       workdir  default ../../browser
#       outdir   default out/QuickBrowser (relative to the checkout)
#
# Run after fetch-source.sh and branding/apply-branding.py. Writes args.gn and
# runs `gn gen`; it does not build. `ninja -C out/QuickBrowser chrome` does.
set -euo pipefail

HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
WORK="${1:-$HERE/../../browser}"
WORK="$(cd "$WORK" && pwd)"
SRC="$WORK/src-checkout/src"
OUT="${2:-out/QuickBrowser}"
UG="$WORK/ungoogled-chromium"

export PATH="$WORK/depot_tools:$PATH"
[ -d "$SRC" ] || { echo "no source tree at $SRC"; exit 1; }
grep -q "PRODUCT_FULLNAME=Quick Browser" \
     "$SRC/chrome/app/theme/chromium/BRANDING" 2>/dev/null \
  || { echo "tree is not branded - run branding/apply-branding.py first"; exit 1; }

# gn and ninja are CIPD deps, and gclient does not reliably materialise them
# here: `gclient sync --reset` clears buildtools/linux64 and does not always put
# it back, so `gn gen` fails with "Could not find gn executable" on a tree that
# is otherwise complete. Rather than re-running sync and hoping, install the
# exact revisions DEPS pins, which is what gclient would have done anyway.
ensure_cipd() {   # $1 package  $2 version  $3 dest-relative-to-src  $4 binary
  [ -x "$SRC/$3/$4" ] && return 0
  echo "   fetching $4 ($2)"
  cipd ensure -root "$SRC/$3" -ensure-file - >/dev/null 2>&1 <<EOF
$1 $2
EOF
  [ -x "$SRC/$3/$4" ] || { echo "!! could not install $4"; return 1; }
}
deps_var() { sed -n "s/^ *'$1': '\([^']*\)'.*/\1/p" "$SRC/DEPS" | head -1; }
GN_VER="$(deps_var gn_version)"
NINJA_PKG="$(deps_var ninja_package)"
NINJA_VER="$(deps_var ninja_version)"
ensure_cipd "gn/gn/linux-amd64" "$GN_VER" "buildtools/linux64" "gn" || exit 1
ensure_cipd "${NINJA_PKG}linux-amd64" "$NINJA_VER" "third_party/ninja" "ninja" || exit 1

mkdir -p "$SRC/$OUT"
ARGS="$SRC/$OUT/args.gn"

{
  echo "# Generated by configure-quick-browser.sh - do not edit by hand."
  echo
  echo "# ---- ungoogled-chromium's own flags, verbatim from its flags.gn ----"
  echo "# Taken as a block on purpose. These are what make the patch series"
  echo "# mean anything: no Google API keys, no Safe Browsing callbacks, no"
  echo "# field trials, no reporting. Editing them individually is how a"
  echo "# 'privacy build' quietly stops being one."
  cat "$UG/flags.gn"
  echo
  cat <<'GN'
# ---- Quick Browser build shape ----
is_debug = false
is_official_build = true      # LTO + full optimisation; this is the product
symbol_level = 0              # no debug symbols: ~30 GB and hours of link saved
blink_symbol_level = 0
is_component_build = false    # one binary, required for a shippable build
enable_nacl = false           # removed from Chrome years ago; dead weight

# ---- Codecs: FREE ONLY. This is a patent decision, not a technical one. ----
# proprietary_codecs=true + ffmpeg_branding="Chrome" would add H.264 and AAC.
# The CODE is open; the FORMATS are covered by the Via LA patent pools and
# QuickOpen holds no licence for them. So some web video will not play, and
# that is the deliberate trade recorded in NOTICE and LICENSING.md section 5.
# Whoever flips this must obtain the patent licences first.
proprietary_codecs = false
ffmpeg_branding = "Chromium"
GN
} > "$ARGS"

echo "== args.gn written to $OUT"
cd "$SRC"
gn gen "$OUT" || { echo "!! gn gen failed"; exit 1; }

echo
echo "== configured"
gn args "$OUT" --list --short --overrides-only | sed 's/^/   /'
echo
echo "   build with:  cd $SRC && ninja -C $OUT chrome"
